FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY ./pyproject.toml ./uv.lock ./README.md /app/
WORKDIR /app
RUN uv sync --frozen --extra mlflow

CMD ["uv", "run", "mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"]
