version: '3'
x-airflow-common: &airflow-common
  image: apache/airflow:2.6.3-python3.10
  environment:
    - AIRFLOW_HOME=/opt/airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    # - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow/mlruns:/mlflow/mlruns
    command: mlflow ui --host 0.0.0.0 --port 5000
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - airflow users list || ( airflow db init && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email )
    restart: on-failure
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    entrypoint: airflow
    command: webserver
    ports:
      - 8080:8080
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    entrypoint: /bin/bash
    command: airflow scheduler
    restart: always