name: Unit tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Run tests
        run: uv run pytest
  laugh:
    runs-on: ubuntu-latest
    steps:
      - name: Laughing
        run: echo "hehehehelp kkkkcry"
